wordpress_sites:
  "147.182.220.101":
    site_hosts:
      - "147.182.220.101"
    local_path: "../site"
    deploy_to: "/srv/www/147.182.220.101"
    repo: "git@github.com:mager19/amica.git"
    branch: "main"
    env:
      wp_home: "http://147.182.220.101"
      wp_siteurl: "http://147.182.220.101/wp"
