mysql_root_password: "{{ vault_mysql_root_password }}" # Define this variable in group_vars/staging/vault.yml

project_root: /www/amicacenter_191/public
www_root: /www/amicacenter_191/public
web_user: amicacenter
web_group: www-data